# Generated by Django 4.2.24 on 2026-02-11 07:29

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OTT', '0002_user_bio_user_hobbies_user_phone_user_profile_pic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='thumbnail_url',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='thumbnail'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='video_url',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='video'),
        ),
    ]
